### ISSUE TITLE
Not able to see available doctor

### ISSUE THREAD

**Issue by AyushBhardwaj944** [gautamgc17/Health-CheckUp#1]
I am to follow all the process and server is getting up, but in the window where we can do "book an appointment" in that i am not able to see doctor.
Can you please me out with this issue?

**Comment by gautamgc17** [comment]
It is not being displayed because the I haven't uploaded the database file on github. So u kindly insert some dummy data into sqlite database. Make the migrations and then go to admin panel of django to add data. Then it will display.
